[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "consistent-pip-requirements"
version = "0.3.0.dev0"
description = "Add your description here"
authors = [{ name = "Scott Searcy", email = "smsearcy@gmail.com" }]
readme = "README.md"
license = "MIT"
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/smsearcy/pre-commit-consistent-pip-requirements"

[project.scripts]
check-requirements = "consistent_pip_requirements.check_requirements:main"

[dependency-groups]
dev = ["basedpyright>=1.22.0", "pytest>=7.4.4", "ruff>=0.8.1"]
lsp = [
    "pylsp-mypy>=0.6.9",
    "pylsp-rope>=0.1.17",
    "python-lsp-ruff>=2.2.2",
    "python-lsp-server>=1.12.0",
]
